kind = "web"
previewPath = "/"
title = "Zain Recharge"
version = "1.0.0"
id = "artifacts/zain-recharge"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26038

[services.development]
run = "pnpm --filter @workspace/zain-recharge run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zain-recharge", "run", "build" ]
serve = "static"
publicDir = "artifacts/zain-recharge/dist"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26038"
BASE_PATH = "/"
